-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 09:02:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SHOPMOVIES
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SHOPMOVIES` ;

-- -----------------------------------------------------
-- Schema SHOPMOVIES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SHOPMOVIES` DEFAULT CHARACTER SET utf8 ;
USE `SHOPMOVIES` ;

-- -----------------------------------------------------
-- Table `SHOPMOVIES`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SHOPMOVIES`.`peliculas` (
  `id_pelicula` INT,
  `titulo` VARCHAR(45) NOT NULL,
  `año` INT NULL,
  `critica` VARCHAR(45) NULL,
  `caratula` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SHOPMOVIES`.`copias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SHOPMOVIES`.`copias` (
  `n_copia` INT,
  `deteriorada` VARCHAR(45) NULL,
  `formato` VARCHAR(45) NOT NULL,
  `id_pelicula` INT NULL,
  `precio_alquiler` INT NULL,
  PRIMARY KEY (`n_copia`),
  CONSTRAINT `peliculas`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `SHOPMOVIES`.`peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `peliculas_idx` ON `SHOPMOVIES`.`copias` (`id_pelicula` ASC);


-- -----------------------------------------------------
-- Table `SHOPMOVIES`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SHOPMOVIES`.`clientes` (
  `cod_cliente` INT,
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `SHOPMOVIES`.`clientes` (`dni` ASC) ;

CREATE UNIQUE INDEX `email_UNIQUE` ON `SHOPMOVIES`.`clientes` (`email` ASC) ;


-- -----------------------------------------------------
-- Table `SHOPMOVIES`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SHOPMOVIES`.`prestamos` (
  `id_prestamo` INT,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_tope` DATE NULL,
  `fecha_entrega` DATE NULL,
  `cod_cliente` INT NULL,
  `n_copia` INT NULL,
  PRIMARY KEY (`id_prestamo`),
  CONSTRAINT `copias`
    FOREIGN KEY (`n_copia`)
    REFERENCES `SHOPMOVIES`.`copias` (`n_copia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_cliente`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `SHOPMOVIES`.`clientes` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `copias_idx` ON `SHOPMOVIES`.`prestamos` (`n_copia` ASC) ;

CREATE INDEX `cod_cliente_idx` ON `SHOPMOVIES`.`prestamos` (`cod_cliente` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
